import type { NextPage } from 'next'
import Head from 'next/head'
import { Table } from '../components/table'
import { SearchInput } from '../components/input/Search/SearchInput'

const Home: NextPage = () => {
    return (
        <div className={'flex justify-center my-24'}>
            <Head>
                <title>Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main
                className={
                    'place-items-center bg-white border-2 rounded-xl w-10/12'
                }
            >
                <SearchInput />
                <Table />
            </main>
        </div>
    )
}

export default Home
